name: Test, build and send to firebase

on:
  pull_request:
    branches:
      - release/*
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      issues: write
      pull-requests: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurando JDK 18
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '18'

      - name: Aplicar permissão
        run: chmod +x gradlew

      - name: Rodando testes
        run: ./gradlew clean test

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: upload artifact to Firebase App Distribution1
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID_ANDROID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: QA
          file: app/build/outputs/apk/release/app-release.apk